services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  petclinic:
    image: petclinic-jdbc-cds
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
